apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy-acc
  namespace: gocd
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: servicenow-discovery-token
  namespace: gocd
  annotations:
    kubernetes.io/service-account.name: "deploy-acc"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: deploy-only
rules:
- apiGroups: [""]
  resources:
  - pods
  - pods/log
  verbs: ["*"]
- apiGroups: [""]
  resources:
  - nodes
  verbs: ["list"]
- apiGroups: [""]
  resources:
  - events
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deploy-only
subjects:
- kind: ServiceAccount
  name: deploy-acc
  namespace: gocd
roleRef:
  kind: ClusterRole
  name: deploy-only
  apiGroup: rbac.authorization.k8s.io